### ISSUE TITLE
callback not be invoked if interval is shorter than `after` param

### ISSUE THREAD

**Issue by zitudu** [bep/debounce#5]
Example:

```go
d := New(1 * time.Second)

for i := 0; i < 10; i++ {
  d(func () {
    println("called")
  })
  time.Sleep(900 * time.Millisecond)
}
// Nothing output.
```

Expected:

"called" should be printed 8~9 times.

**Comment by davidrenne** [comment]
It's highly unlikely the author will fix this due to 1400 repos on github, it would unexpectedly be firing stuff that people are relying on it not firing.  I would suggest using:

https://github.com/vnteamopen/godebouncer

It works in this use case and I just submitted a PR to it which fixed a nil error when I tried a case like yours firing early.  I too would expect a debouncer would fire once if my invocation was early but I think he clears the timer and resets it so the time.Afterfunc cant fire in your case.

**Comment by zitudu** [comment]
> It's highly unlikely the author will fix this due to 1400 repos on github, it would unexpectedly be firing stuff that people are relying on it not firing. I would suggest using:
> 
> https://github.com/vnteamopen/godebouncer
> 
> It works in this use case and I just submitted a PR to it which fixed a nil error when I tried a case like yours firing early. I too would expect a debouncer would fire once if my invocation was early but I think he clears the timer and resets it so the time.Afterfunc cant fire in your case.

That's what I need. Thanks.
